/* public.AccessURL */
create table public.AccessURL
(
   AccessURL varchar(200) not null,
   PortalClientID integer not null,
   constraint pk_accessurl primary key (AccessURL)
);

/* public.ApiAuthorization */
create table public.ApiAuthorization
(
   ID integer generated by default as identity (start with 1) not null,
   PortalUserID integer,
   ApiSecret varchar(200),
   RefreshToken character large object,
   constraint pk_apiauthorization primary key (ApiSecret)
);

create index ix_apiauthorization1 on public.ApiAuthorization (PortalUserID);

/* public.Audit */
create table public.Audit
(
   ID bigint generated by default as identity (start with 1) not null,
   ChangedBy varchar(254) not null,
   ChangedOn timestamp not null,
   RecordID varchar(255),
   RecordName varchar(500) not null,
   Category varchar(100) not null,
   Item varchar(100) not null,
   Change enum('A','D','M') not null,
   OldValue character large object,
   NewValue character large object,
   PortalClientID integer not null,
   constraint pk_audit primary key (ID)
);

create index ix_audit1 on public.Audit (ChangedOn,PortalClientID);

/* public.AutomationAuthorization */
create table public.AutomationAuthorization
(
   AutomationSecret uuid default random_uuid(7) not null,
   RefreshToken character large object not null,
   ExpirationDateTime timestamp not null,
   CreatedOnDateTime timestamp not null,
   LastUsedDateTime timestamp,
   PortalUserID integer not null,
   constraint pk_automationauthorization primary key (AutomationSecret)
);

create index ix_automationauthorization1 on public.AutomationAuthorization (PortalUserID);

/* public.Brand */
create table public.Brand
(
   ID integer generated by default as identity (start with 1) not null,
   Name character large object not null,
   constraint pk_brand primary key (ID),
   constraint ak_brand1 unique (Name)
);

insert into Brand (Name) values ('Hilton');
            insert into Brand (Name) values ('Marriott International');
            insert into Brand (Name) values ('Hyatt Hotels Corporation');
            insert into Brand (Name) values ('IHG Hotels & Resorts');
            insert into Brand (Name) values ('Choice Hotels');
            insert into Brand (Name) values ('Wyndham Hotels & Resorts');
            insert into Brand (Name) values ('Other Notable Brands & Independent Collections');;

/* public.Certificate */
create table public.Certificate
(
   Alias character large object not null,
   Certificate character large object,
   PrivateKey character large object,
   constraint pk_certificate primary key (Alias)
);

/* public.ClientPreference */
create table public.ClientPreference
(
   ID bigint generated by default as identity (start with 1) not null,
   PortalClientID integer not null,
   PrefKey varchar(200) not null,
   PrefValue character large object not null,
   constraint pk_clientpreference primary key (ID),
   constraint ak_clientpreference1 unique (PortalClientID,PrefKey)
);

/* public.ClientProduct */
create table public.ClientProduct
(
   ClientID integer not null,
   ProductID integer not null,
   constraint pk_clientproduct primary key (ClientID,ProductID)
);

/* public.ClientRegion */
create table public.ClientRegion
(
   ID integer generated by default as identity (start with 1) not null,
   PortalClientID integer not null,
   Name character large object not null,
   ShortName varchar(25) not null,
   Code varchar(25) not null,
   ExcludeFromCorpReports char(1) default 'N' not null,
   constraint pk_clientregion primary key (ID),
   constraint ak_clientregion1 unique (PortalClientID,Name),
   constraint ak_clientregion2 unique (PortalClientID,Code),
   constraint ck_clientreg_excludefr_857B8591 check(ExcludeFromCorpReports in ('Y','N'))
);

/* public.CredentialsHistory */
create table public.CredentialsHistory
(
   Credentials varchar(500) not null,
   CredentialsDateTime timestamp not null,
   constraint pk_credentialshistory primary key (Credentials)
);

create index ix_credentialshistory1 on public.CredentialsHistory (CredentialsDateTime);

/* public.ExpiredCredentials */
create table public.ExpiredCredentials
(
   Credentials varchar(500) not null,
   ExpiredOnDateTime timestamp not null,
   constraint pk_expiredcredentials primary key (Credentials)
);

/* public.GlobalData */
create table public.GlobalData
(
   ID integer generated by default as identity (start with 1) not null,
   Tag varchar(50) not null,
   TagValue character large object,
   TagData binary large object,
   constraint pk_globaldata primary key (ID),
   constraint ak_globaldata1 unique (Tag)
);

/* public.ImpersonateHistory */
create table public.ImpersonateHistory
(
   PortalUserIDToImpersonate integer not null,
   PortalUserIDOfImpersonator integer not null,
   LoginDateTime timestamp not null,
   constraint pk_impersonatehistory primary key (PortalUserIDToImpersonate,PortalUserIDOfImpersonator,LoginDateTime)
);

/* public.LDAPConfig */
create table public.LDAPConfig
(
   ID integer generated by default as identity (start with 1) not null,
   URL varchar(200) not null,
   BaseDN varchar(200) not null,
   SearchFilter varchar(200) not null,
   Domain varchar(200),
   UserNamePattern varchar(200),
   constraint pk_ldapconfig primary key (ID)
);

/* public.LoginHistory */
create table public.LoginHistory
(
   ID integer generated by default as identity (start with 1) not null,
   PortalUserID integer,
   LoginDateTime timestamp not null,
   LoginStatus varchar(50) not null,
   DatabaseID integer,
   PropertyID integer,
   PropertyName varchar(50),
   LoginID varchar(254),
   FailureReason character large object,
   constraint pk_loginhistory primary key (PortalUserID,LoginDateTime,LoginStatus)
);

/* public.NewUserRegistration */
create table public.NewUserRegistration
(
   ID uuid default random_uuid(7) not null,
   Type enum('EMPLOYEE','USER') not null,
   PartnerCode character large object not null,
   LoginID character large object not null,
   VerificationCode character large object not null,
   ClientID integer not null,
   LoginClientID integer not null,
   CreatedOn timestamp not null,
   CreatedByPortalUserID integer not null,
   UpdatedByPortalUserID integer,
   ExpiresOn timestamp not null,
   NumberVerifyFailures integer not null,
   NumberOfAttempts integer,
   StartedOn timestamp,
   CompletedOn timestamp,
   PortalUserID integer,
   DatabaseID integer,
   PropertyID integer,
   EmployeeID integer,
   Email character large object,
   MobilePhone character large object,
   FirstName character large object,
   MiddleName character large object,
   LastName character large object,
   Locale character large object,
   constraint pk_newuserregistration primary key (ID),
   constraint ak_newuserregistration1 unique (PartnerCode,LoginID,VerificationCode)
);

/* public.PasswordBlacklist */
create table public.PasswordBlacklist
(
   ID integer generated by default as identity (start with 1) not null,
   PasswordPattern varchar(255) not null,
   constraint pk_passwordblacklist primary key (ID),
   constraint ak_passwordblacklist1 unique (PasswordPattern)
);

/* public.PasswordQuestion */
create table public.PasswordQuestion
(
   ID integer generated by default as identity (start with 1) not null,
   Locale varchar(10) not null,
   Question varchar(255) not null,
   constraint pk_passwordquestion primary key (ID),
   constraint ak_passwordquestion1 unique (Locale,Question)
);

/* public.PasswordRules */
create table public.PasswordRules
(
   ID integer generated by default as identity (start with 1) not null,
   Pattern varchar(100) not null,
   Description varchar(200) not null,
   Duration smallint,
   ExpirationWarning smallint,
   NumberPrior smallint,
   MaxAttempts smallint,
   ResetsPerDay integer default 3 not null,
   constraint pk_passwordrules primary key (ID),
   constraint ck_passwordr_duration_D74EEB37 check(Duration >= 1),
   constraint ck_passwordr_expiratio_EF8FDBCA check(ExpirationWarning >= 1),
   constraint ck_passwordr_numberpri_F247D89E check(NumberPrior >= 0),
   constraint ck_passwordr_resetsper_E8192F86 check(ResetsPerDay >= 1 and ResetsPerDay <= 3)
);

/* public.PortalAdminUserAdditionalClients */
create table public.PortalAdminUserAdditionalClients
(
   ID integer generated by default as identity (start with 1) not null,
   UserID integer not null,
   ClientID integer not null,
   constraint pk_portaladminuseradditionalclients primary key (ID),
   constraint ak_portaladminuseradditionalclients1 unique (UserID,ClientID)
);

/* public.PortalClient */
create table public.PortalClient
(
   ID integer generated by default as identity (start with 1) not null,
   GlobalID uuid default random_uuid(7) not null,
   Name varchar(50) not null,
   Code varchar(25) not null,
   Active char(1) default 'Y' not null,
   ParentClientID integer,
   DatabaseID integer,
   KioskURL varchar(255),
   License binary large object,
   ValidPattern varchar(100),
   ValidDescription varchar(200),
   Duration smallint,
   NumberPrior smallint,
   MaxAttempts smallint,
   AccessURL varchar(200),
   RedirectURL varchar(200),
   LDAPID integer,
   SAMLID integer,
   PasswordRulesID integer,
   ImpersonationEnabled char(1) default 'N' not null,
   Type enum('LDAP','SAML','UNIPORTAL') default 'UNIPORTAL' not null,
   ExpirationWarning smallint,
   InviteLoginClientID integer,
   ManagerInviteLoginClientID integer,
   AutomationApiSecret character large object,
   constraint pk_portalclient primary key (ID),
   constraint ak_portalclient1 unique (GlobalID),
   constraint ak_portalclient2 unique (Name),
   constraint ck_portalcli_active_AFB1450E check(Active in ('Y','N')),
   constraint ck_portalcli_impersona_D4186AAD check(ImpersonationEnabled in ('Y','N')),
   constraint ck_portalcli_expiratio_F18A7705 check(ExpirationWarning >= 1)
);

/* public.PortalProperty */
create table public.PortalProperty
(
   ID uuid default random_uuid(7) not null,
   PortalClientID integer not null,
   Name character large object not null,
   Code character large object not null,
   Active char(1) default 'Y' not null,
   License character large object not null,
   TimeZoneID character large object not null,
   DefaultLocale character large object default 'en-US' not null,
   TapsDatabaseID integer,
   PropertyType enum('FULL_SERVICE_HOTEL','SELECT_SERVICE_HOTEL','EXTENDED_STAY_HOTEL','RESORT','BOUTIQUE_HOTEL','CONVENTION_HOTEL','CASINO_HOTEL','MIXED_USE','LIMITED_SERVICE_HOTEL','ALL_INCLUSIVE_RESORT','TIMESHARE','GOLF_COURSE','RESTAURANT','OTHER'),
   MarketType enum('URBAN','SUBURBAN','AIRPORT','RESORT','SMALL_TOWN','HIGHWAY','CONVENTION','CAMPUS','OTHER'),
   BrandID integer,
   NumberRooms integer,
   AddressLine1 character large object not null,
   AddressLine2 character large object,
   Locality character large object not null,
   AdministrativeArea character large object not null,
   PostalCode character large object not null,
   Country character large object not null,
   ClientRegionID integer,
   Unionized char(1) default 'N',
   OpsDateFormat character large object default 'MM/dd/yyyy' not null,
   LogoReference character large object,
   constraint pk_portalproperty primary key (ID),
   constraint ak_portalproperty1 unique (PortalClientID,Name),
   constraint ak_portalproperty2 unique (PortalClientID,Code),
   constraint ck_portalpro_active_1D4166C4 check(Active in ('Y','N')),
   constraint ck_portalpro_unionized_4DC70061 check(Unionized in ('Y','N'))
);

/* public.PortalPropertyAdditionalLocale */
create table public.PortalPropertyAdditionalLocale
(
   ID uuid default random_uuid(7) not null,
   PortalPropertyID uuid not null,
   Locale character large object not null,
   constraint pk_portalpropertyadditionallocale primary key (ID),
   constraint ak_portalpropertyadditionallocale1 unique (PortalPropertyID,Locale)
);

/* public.PortalUser */
create table public.PortalUser
(
   ID integer generated by default as identity (start with 1) not null,
   LoginClientID integer,
   LoginId varchar(254) not null,
   GlobalID uuid default random_uuid(7) not null,
   PWord varchar(200) not null,
   Active char(1) default 'N',
   ActiveChangedOn timestamp,
   FirstName varchar(50),
   MiddleName varchar(50),
   LastName varchar(50),
   EMail varchar(254),
   MobilePhone varchar(100),
   QuestionID integer,
   Answer varchar(100),
   LastLogin timestamp,
   PwordChanged timestamp,
   PwordChangedSameDayCount integer,
   Locale varchar(10),
   ClientID integer,
   DefaultDatabaseID integer,
   BypassLdap char(1) default 'N' not null,
   LdapUserName varchar(254),
   Flags integer,
   Photo binary large object,
   CreatedOn timestamp,
   CreatedByPortalUserID integer,
   CanAdministerUsers char(1) default 'N' not null,
   constraint pk_portaluser primary key (ID),
   constraint ak_portaluser1 unique (LoginClientID,LoginId),
   constraint ak_portaluser2 unique (GlobalID),
   constraint ck_portaluse_active_EAC5020E check(Active in ('Y','N')),
   constraint ck_portaluse_bypasslda_84871397 check(BypassLdap in ('Y','N')),
   constraint ck_portaluse_canadmini_7918778 check(CanAdministerUsers in ('Y','N'))
);

create index ix_portaluser1 on public.PortalUser (EMail);

/* public.PortalUserAudit */
create table public.PortalUserAudit
(
   ID bigint generated by default as identity (start with 1) not null,
   PortalUserID integer not null,
   LoginClientID integer,
   LoginId varchar(254) not null,
   PWord varchar(200) not null,
   Active char(1) default 'N',
   FirstName varchar(50),
   MiddleName varchar(50),
   LastName varchar(50),
   EMail varchar(254),
   MobilePhone varchar(100),
   QuestionID integer,
   Answer varchar(100),
   LastLogin timestamp,
   PwordChanged timestamp,
   Locale varchar(10),
   ClientID integer,
   DefaultDatabaseID integer,
   BypassLdap char(1) default 'N' not null,
   LdapUserName varchar(254),
   Flags integer,
   ChangedOn timestamp not null,
   Operation char(1) not null,
   Command character large object not null,
   HostName varchar(128) not null,
   ChangedBySqlUser varchar(128) not null,
   ChangedByPortalUserID integer,
   CanAdministerUsers char(1) default 'N',
   constraint pk_portaluseraudit primary key (ID),
   constraint ck_portaluse_active_855DA7A1 check(Active in ('Y','N')),
   constraint ck_portaluse_bypasslda_305CB7AA check(BypassLdap in ('Y','N')),
   constraint ck_portaluse_canadmini_E697688B check(CanAdministerUsers in ('Y','N'))
);

create index ix_portaluseraudit1 on public.PortalUserAudit (LoginId,ChangedOn);
create index ix_portaluseraudit2 on public.PortalUserAudit (ChangedOn,LoginId);

/* public.PortalUserPropertyAccess */
create table public.PortalUserPropertyAccess
(
   ID uuid default random_uuid(7) not null,
   PortalUserID integer not null,
   PortalPropertyID uuid not null,
   TapsEnabled char(1) default 'N' not null,
   OpsEnabled char(1) default 'N' not null,
   SurveyEnabled char(1) default 'N' not null,
   TapsAdmin char(1) default 'N' not null,
   constraint pk_portaluserpropertyaccess primary key (ID),
   constraint ak_portaluserpropertyaccess1 unique (PortalUserID,PortalPropertyID),
   constraint ck_portaluse_tapsenabl_C711A7C2 check(TapsEnabled in ('Y','N')),
   constraint ck_portaluse_opsenable_D6D18E7E check(OpsEnabled in ('Y','N')),
   constraint ck_portaluse_surveyena_596E2A18 check(SurveyEnabled in ('Y','N')),
   constraint ck_portaluse_tapsadmin_F3B74C10 check(TapsAdmin in ('Y','N'))
);

/* public.PortalUserRegistration */
create table public.PortalUserRegistration
(
   ID bigint generated by default as identity (start with 1) not null,
   PortalUserID integer not null,
   ExpiresOn timestamp not null,
   RegisteredOn timestamp,
   InvitedOn timestamp not null,
   InvitedByPortalUserID integer not null,
   NumberVerifyFailures integer default 0 not null,
   VerificationCode integer,
   constraint pk_portaluserregistration primary key (ID),
   constraint ak_portaluserregistration1 unique (PortalUserID)
);

/* public.Product */
create table public.Product
(
   ID integer generated by default as identity (start with 1) not null,
   Code varchar(25) not null,
   Name varchar(200) not null,
   URL varchar(255),
   RequiredUserType enum('LOYALTY','RMS','OTHER'),
   RequiredDeviceTypes varchar(200),
   constraint pk_product primary key (ID),
   constraint ak_product1 unique (Code),
   constraint ak_product2 unique (Name)
);

/* public.ProtectedApiAccessKey */
create table public.ProtectedApiAccessKey
(
   AccessKey varchar(2000) not null,
   constraint pk_protectedapiaccesskey primary key (AccessKey)
);

/* public.RemoteServiceProvider */
create table public.RemoteServiceProvider
(
   Name varchar(100) not null,
   DatabaseID integer,
   URL varchar(255) not null,
   constraint pk_remoteserviceprovider primary key (Name,DatabaseID)
);

/* public.SAMLConfig */
create table public.SAMLConfig
(
   ID integer generated by default as identity (start with 1) not null,
   URL varchar(200) not null,
   SignatureMethodName varchar(50),
   SignatureMethodUri varchar(100),
   DigestMethod varchar(100),
   ProtocolBinding varchar(100),
   SpNameQualifier varchar(100),
   AuthnContextClassref varchar(100),
   NameidPolicyFormat varchar(100),
   KeystoreAlias varchar(50),
   UsernameVariable varchar(50),
   EmailVariable varchar(50),
   PropertyCodeVariable varchar(50),
   DisplayNameVariable varchar(50),
   EmployeeIdVariable varchar(50),
   EnableAutoRegistration char(1) default 'N' not null,
   SignRequestKeystoreAlias varchar(50),
   SignResponseKeystoreAlias varchar(50),
   DecryptResponseKeystoreAlias varchar(50),
   UserAutoMigrationType character large object,
   AutoLinkEmployeeForManagersType character large object,
   UseAltEmpID char(1) default 'N' not null,
   KeepMeSignedInDeviceTypes character large object,
   LogOffUrl character large object,
   ForceAuthn char(1) default 'N',
   constraint pk_samlconfig primary key (ID),
   constraint ck_samlconfi_enableaut_F1EA9BBB check(EnableAutoRegistration in ('Y','N')),
   constraint ck_samlconfi_usealtemp_87436811 check(UseAltEmpID in ('Y','N')),
   constraint ck_samlconfi_forceauth_BBF0840B check(ForceAuthn in ('Y','N'))
);

/* public.SAMLIDPConfig */
create table public.SAMLIDPConfig
(
   ID integer generated by default as identity (start with 1) not null,
   PortalClientID integer not null,
   ExternalProductName varchar(50),
   ExternalProductCode varchar(2),
   SAMLVersion varchar(10) default 2.0 not null,
   PostbackURL character large object not null,
   UserNameVariable varchar(254) default 'Username' not null,
   KeystoreAlias varchar(25),
   SignRequestKeystoreAlias varchar(25),
   SignResponseKeystoreAlias varchar(25),
   DecryptResponseKeystoreAlias varchar(25),
   constraint pk_samlidpconfig primary key (ID),
   constraint ak_samlidpconfig1 unique (PortalClientID,ExternalProductCode)
);

/* public.Session */
create table public.Session
(
   ID integer generated by default as identity (start with 1) not null,
   SessionID varchar(255) not null,
   Host varchar(255) not null,
   SessionTime timestamp not null,
   constraint pk_session primary key (ID),
   constraint ak_session1 unique (SessionID)
);

create index ix_session1 on public.Session (Host);

/* public.SessionHistory */
create table public.SessionHistory
(
   ID integer generated by default as identity (start with 1) not null,
   SessionID varchar(255) not null,
   Host varchar(255) not null,
   LoginID varchar(254),
   LoginDT timestamp,
   LogoutDT timestamp,
   TimedOut char(1) default 'N',
   DatabaseID integer,
   DatabaseName varchar(50),
   PropertyID integer,
   PropertyName varchar(50),
   constraint pk_sessionhistory primary key (ID),
   constraint ak_sessionhistory1 unique (SessionID),
   constraint ck_sessionhi_timedout_9051298 check(TimedOut in ('Y','N'))
);

create index ix_sessionhistory1 on public.SessionHistory (Host);
create index ix_sessionhistory2 on public.SessionHistory (LoginID,LoginDT);

/* public.SystemMessage */
create table public.SystemMessage
(
   ID integer generated by default as identity (start with 1) not null,
   StartTime timestamp not null,
   EndTime timestamp not null,
   MsgText character large object,
   constraint pk_systemmessage primary key (ID)
);

create index ix_systemmessage1 on public.SystemMessage (StartTime,EndTime);

/* public.TermsAndConditionsTextOverride */
create table public.TermsAndConditionsTextOverride
(
   ClientID integer not null,
   Locale character large object not null,
   DisplayText character large object not null,
   constraint pk_termsandconditionstextoverride primary key (ClientID,Locale)
);

/* public.URLConfig */
create table public.URLConfig
(
   Name varchar(255) not null,
   URL varchar(255) not null,
   constraint pk_urlconfig primary key (Name)
);

/* public.UserData */
create table public.UserData
(
   ID integer generated by default as identity (start with 1) not null,
   UserID integer not null,
   Tag varchar(50) not null,
   TagValue varchar(255),
   TagData binary large object,
   constraint pk_userdata primary key (ID),
   constraint ak_userdata1 unique (UserID,Tag)
);

/* public.UserDatabase */
create table public.UserDatabase
(
   UserID integer not null,
   DatabaseID integer not null,
   constraint pk_userdatabase primary key (UserID,DatabaseID)
);

/* public.UserFailedPassword */
create table public.UserFailedPassword
(
   ID integer generated by default as identity (start with 1) not null,
   UserID integer not null,
   AttemptedOn timestamp not null,
   PWord varchar(200) not null,
   constraint pk_userfailedpassword primary key (ID),
   constraint ak_userfailedpassword1 unique (UserID,AttemptedOn)
);

/* public.UserPreference */
create table public.UserPreference
(
   ID bigint generated by default as identity (start with 1) not null,
   UserID integer not null,
   PrefKey varchar(200) not null,
   PrefValue character large object not null,
   constraint pk_userpreference primary key (ID),
   constraint ak_userpreference1 unique (UserID,PrefKey)
);

/* public.UserPriorPassword */
create table public.UserPriorPassword
(
   ID integer generated by default as identity (start with 1) not null,
   UserID integer not null,
   EffDate timestamp not null,
   PWord varchar(200) not null,
   constraint pk_userpriorpassword primary key (ID),
   constraint ak_userpriorpassword1 unique (UserID,EffDate)
);

/* public.UserRefreshToken */
create table public.UserRefreshToken
(
   UserID integer not null,
   RefreshToken character large object not null,
   constraint pk_userrefreshtoken primary key (UserID)
);

/* public.UserRegistration */
create table public.UserRegistration
(
   ID bigint generated by default as identity (start with 1) not null,
   LoginID varchar(254) not null,
   EMail varchar(254),
   ClientID integer not null,
   LoginClientID integer,
   DatabaseID integer not null,
   PropertyID integer not null,
   EmployeeID integer not null,
   EmpID varchar(25) not null,
   FirstName varchar(50) not null,
   MiddleName varchar(50) not null,
   LastName varchar(50) not null,
   ExpiresOn timestamp not null,
   RegisteredOn timestamp,
   OptOut char(1) default 'N' not null,
   NumberVerifyFailures integer default 0 not null,
   NumberOfAttempts integer default 0 not null,
   Locale varchar(10),
   VerificationCode integer,
   CreatedByPortalUserID integer,
   UpdatedByPortalUserID integer,
   constraint pk_userregistration primary key (ID),
   constraint ak_userregistration1 unique (LoginID,ClientID,DatabaseID,PropertyID,EmployeeID),
   constraint ck_userregis_optout_63E35456 check(OptOut in ('Y','N'))
);

/* public.WatsonDatabase */
create table public.WatsonDatabase
(
   ID integer generated by default as identity (start with 1) not null,
   Name varchar(50) not null,
   DatabaseURL varchar(255) not null,
   DatabaseUserName varchar(200) not null,
   DatabasePassword varchar(200) not null,
   DatabaseDriver varchar(255) not null,
   RedirectURL varchar(255),
   MobileRedirectURL varchar(255),
   ApiURL varchar(255),
   LoginURL varchar(255),
   WatsonVersion varchar(10),
   OlapDatabaseURL varchar(255),
   OlapDatabaseUserName varchar(200),
   OlapDatabasePassword varchar(200),
   constraint pk_watsondatabase primary key (ID),
   constraint ak_watsondatabase1 unique (Name)
);

/* relations */
alter table public.AccessURL add constraint fk_accessurl1 foreign key (PortalClientID) references public.PortalClient(ID) on delete no action;
alter table public.ApiAuthorization add constraint fk_apiauthorization1 foreign key (PortalUserID) references public.PortalUser(ID) on delete cascade;
alter table public.AutomationAuthorization add constraint fk_automationauthorization1 foreign key (PortalUserID) references public.PortalUser(ID) on delete cascade;
alter table public.ClientPreference add constraint fk_clientpreference1 foreign key (PortalClientID) references public.PortalClient(ID) on delete cascade;
alter table public.ClientProduct add constraint fk_clientproduct1 foreign key (ClientID) references public.PortalClient(ID) on delete cascade;
alter table public.ClientProduct add constraint fk_clientproduct2 foreign key (ProductID) references public.Product(ID) on delete cascade;
alter table public.ClientRegion add constraint fk_clientregion1 foreign key (PortalClientID) references public.PortalClient(ID) on delete cascade;
alter table public.ImpersonateHistory add constraint fk_impersonatehistory1 foreign key (PortalUserIDToImpersonate) references public.PortalUser(ID) on delete cascade;
alter table public.ImpersonateHistory add constraint fk_impersonatehistory2 foreign key (PortalUserIDOfImpersonator) references public.PortalUser(ID) on delete cascade;
alter table public.LoginHistory add constraint fk_loginhistory1 foreign key (PortalUserID) references public.PortalUser(ID) on delete cascade;
alter table public.LoginHistory add constraint fk_loginhistory2 foreign key (DatabaseID) references public.WatsonDatabase(ID) on delete cascade;
alter table public.NewUserRegistration add constraint fk_newuserregistration1 foreign key (ClientID) references public.PortalClient(ID) on delete cascade;
alter table public.NewUserRegistration add constraint fk_newuserregistration2 foreign key (LoginClientID) references public.PortalClient(ID) on delete cascade;
alter table public.NewUserRegistration add constraint fk_newuserregistration3 foreign key (CreatedByPortalUserID) references public.PortalUser(ID) on delete cascade;
alter table public.NewUserRegistration add constraint fk_newuserregistration4 foreign key (UpdatedByPortalUserID) references public.PortalUser(ID) on delete cascade;
alter table public.NewUserRegistration add constraint fk_newuserregistration5 foreign key (DatabaseID) references public.WatsonDatabase(ID) on delete cascade;
alter table public.NewUserRegistration add constraint fk_newuserregistration6 foreign key (PortalUserID) references public.PortalUser(ID) on delete cascade;
alter table public.PortalAdminUserAdditionalClients add constraint fk_portaladminuseradditionalclients1 foreign key (UserID) references public.PortalUser(ID) on delete cascade;
alter table public.PortalAdminUserAdditionalClients add constraint fk_portaladminuseradditionalclients2 foreign key (ClientID) references public.PortalClient(ID) on delete cascade;
alter table public.PortalClient add constraint fk_portalclient1 foreign key (ParentClientID) references public.PortalClient(ID) on delete cascade;
alter table public.PortalClient add constraint fk_portalclient2 foreign key (DatabaseID) references public.WatsonDatabase(ID) on delete set null;
alter table public.PortalClient add constraint fk_portalclient3 foreign key (PasswordRulesID) references public.PasswordRules(ID) on delete set null;
alter table public.PortalClient add constraint fk_portalclient4 foreign key (LDAPID) references public.LDAPConfig(ID) on delete set null;
alter table public.PortalClient add constraint fk_portalclient5 foreign key (SAMLID) references public.SAMLConfig(ID) on delete set null;
alter table public.PortalClient add constraint fk_portalclient6 foreign key (InviteLoginClientID) references public.PortalClient(ID) on delete cascade;
alter table public.PortalClient add constraint fk_portalclient7 foreign key (ManagerInviteLoginClientID) references public.PortalClient(ID) on delete cascade;
alter table public.PortalProperty add constraint fk_portalproperty1 foreign key (PortalClientID) references public.PortalClient(ID) on delete cascade;
alter table public.PortalProperty add constraint fk_portalproperty2 foreign key (TapsDatabaseID) references public.WatsonDatabase(ID) on delete set null;
alter table public.PortalProperty add constraint fk_portalproperty3 foreign key (BrandID) references public.Brand(ID) on delete set null;
alter table public.PortalProperty add constraint fk_portalproperty4 foreign key (ClientRegionID) references public.ClientRegion(ID) on delete set null;
alter table public.PortalPropertyAdditionalLocale add constraint fk_portalpropertyadditionallocale1 foreign key (PortalPropertyID) references public.PortalProperty(ID) on delete cascade;
alter table public.PortalUser add constraint fk_portaluser1 foreign key (QuestionID) references public.PasswordQuestion(ID) on delete no action;
alter table public.PortalUser add constraint fk_portaluser2 foreign key (LoginClientID) references public.PortalClient(ID) on delete no action;
alter table public.PortalUser add constraint fk_portaluser3 foreign key (ClientID) references public.PortalClient(ID) on delete no action;
alter table public.PortalUser add constraint fk_portaluser4 foreign key (DefaultDatabaseID) references public.WatsonDatabase(ID) on delete set null;
alter table public.PortalUser add constraint fk_portaluser5 foreign key (CreatedByPortalUserID) references public.PortalUser(ID) on delete set null;
alter table public.PortalUserPropertyAccess add constraint fk_portaluserpropertyaccess1 foreign key (PortalUserID) references public.PortalUser(ID) on delete cascade;
alter table public.PortalUserPropertyAccess add constraint fk_portaluserpropertyaccess2 foreign key (PortalPropertyID) references public.PortalProperty(ID) on delete cascade;
alter table public.PortalUserRegistration add constraint fk_portaluserregistration1 foreign key (PortalUserID) references public.PortalUser(ID) on delete cascade;
alter table public.PortalUserRegistration add constraint fk_portaluserregistration2 foreign key (InvitedByPortalUserID) references public.PortalUser(ID) on delete cascade;
alter table public.SAMLIDPConfig add constraint fk_samlidpconfig1 foreign key (PortalClientID) references public.PortalClient(ID) on delete cascade;
alter table public.TermsAndConditionsTextOverride add constraint fk_termsandconditionstextoverride1 foreign key (ClientID) references public.PortalClient(ID) on delete cascade;
alter table public.UserData add constraint fk_userdata1 foreign key (UserID) references public.PortalUser(ID) on delete cascade;
alter table public.UserDatabase add constraint fk_userdatabase1 foreign key (UserID) references public.PortalUser(ID) on delete cascade;
alter table public.UserDatabase add constraint fk_userdatabase2 foreign key (DatabaseID) references public.WatsonDatabase(ID) on delete cascade;
alter table public.UserFailedPassword add constraint fk_userfailedpassword1 foreign key (UserID) references public.PortalUser(ID) on delete cascade;
alter table public.UserPreference add constraint fk_userpreference1 foreign key (UserID) references public.PortalUser(ID) on delete cascade;
alter table public.UserPriorPassword add constraint fk_userpriorpassword1 foreign key (UserID) references public.PortalUser(ID) on delete cascade;
alter table public.UserRefreshToken add constraint fk_userrefreshtoken1 foreign key (UserID) references public.PortalUser(ID) on delete cascade;
alter table public.UserRegistration add constraint fk_userregistration1 foreign key (CreatedByPortalUserID) references public.PortalUser(ID) on delete cascade;
alter table public.UserRegistration add constraint fk_userregistration2 foreign key (UpdatedByPortalUserID) references public.PortalUser(ID) on delete cascade;

drop view UserDatabaseQuery if exists;
create view UserDatabaseQuery as
   select u.ID as UserID,u.LoginId as LoginId,u.EMail,u.Flags,d.ID as DatabaseID,d.Name as DatabaseName,d.DatabaseURL,d.DatabaseUserName,d.DatabasePassword,d.DatabaseDriver,d.RedirectURL from PortalUser u,WatsonDatabase d,UserDatabase ud where u.ID = ud.UserID and d.ID = ud.DatabaseID;

