package com.stano.schema.installer.flyway;

import com.stano.schema.migrations.MigrationServices;
import com.stano.schema.model.DatabaseType;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

public class FlywayDatabaseUpgradeLog {
  private MigrationServices migrationServices = new MigrationServices();

  public int start(DatabaseType databaseType, Connection connection, String changeLogResource) {
    boolean autoCommit;
    try {
      autoCommit = connection.getAutoCommit();
    } catch (SQLException x) {
      throw new FlywayRuntimeException(x);
    }

    try {
      connection.setAutoCommit(false);

      ensureDatabaseUpgradeLogTableExists(databaseType, connection);

      int id;
      try (Statement statement = connection.createStatement()) {
        statement.executeUpdate(
            String.format(
                "insert into databaseupgradelog (StartDateTime,ChangeLogName) values"
                    + " (CURRENT_TIMESTAMP,%s)", // NON-NLS
                quoteSql(changeLogResource.substring(changeLogResource.lastIndexOf("/") + 1))),
            Statement.RETURN_GENERATED_KEYS);

        try (ResultSet rs = statement.getGeneratedKeys()) {
          id = rs.next() ? rs.getInt(1) : 0;
        }
      }

      connection.commit();
      return id;
    } catch (Throwable x) {
      try {
        connection.rollback();
      } catch (SQLException rollbackEx) {
        x.addSuppressed(rollbackEx);
      }
      throw x instanceof FlywayRuntimeException fre ? fre : new FlywayRuntimeException(x);
    } finally {
      try {
        connection.setAutoCommit(autoCommit);
      } catch (SQLException ignored) {
      }
    }
  }

  public void finish(Connection connection, int databaseChangeLogId, String error) {
    boolean autoCommit;
    try {
      autoCommit = connection.getAutoCommit();
    } catch (SQLException x) {
      throw new FlywayRuntimeException(x);
    }

    try {
      connection.setAutoCommit(false);

      try (Statement statement = connection.createStatement()) {
        if (error != null) {
          statement.executeUpdate(
              String.format(
                  "update databaseupgradelog set EndDateTime = CURRENT_TIMESTAMP, Error ="
                      + " %s where ID = %d", // NON-NLS
                  quoteSql(error), databaseChangeLogId));
        } else {
          statement.executeUpdate(
              String.format(
                  "update databaseupgradelog set EndDateTime = CURRENT_TIMESTAMP where ID ="
                      + " %d", // NON-NLS
                  databaseChangeLogId));
        }
      }

      connection.commit();
    } catch (Throwable x) {
      try {
        connection.rollback();
      } catch (SQLException rollbackEx) {
        x.addSuppressed(rollbackEx);
      }
      throw x instanceof FlywayRuntimeException fre ? fre : new FlywayRuntimeException(x);
    } finally {
      try {
        connection.setAutoCommit(autoCommit);
      } catch (SQLException ignored) {
      }
    }
  }

  private void ensureDatabaseUpgradeLogTableExists(DatabaseType databaseType, Connection connection)
      throws SQLException {
    if (!databaseUpgradeLogTableExists(connection)) {
      try (Statement statement = connection.createStatement()) {
        statement.executeUpdate(getDatabaseUpgradeLogDDL(databaseType));
      }
    }
  }

  private String getDatabaseUpgradeLogDDL(DatabaseType databaseType) {
    return switch (databaseType) {
      case SQL_SERVER ->
          "create table dbo.databaseupgradelog (ID integer identity(1,1) not null,StartDateTime"
              + " datetime not null,EndDateTime datetime,ChangeLogName varchar(max),Error"
              + " varchar(max),constraint pk_databaseupgradelog primary key (ID))"; // NON-NLS
      case POSTGRESQL ->
          "create table databaseupgradelog (ID serial not null,StartDateTime timestamp not"
              + " null,EndDateTime timestamp,ChangeLogName text,Error text,constraint"
              + " pk_databaseupgradelog primary key (ID))"; // NON-NLS
      case H2 ->
          "create table databaseupgradelog (ID integer generated by default as identity (start with"
              + " 1) not null,StartDateTime datetime not null,EndDateTime datetime,ChangeLogName"
              + " longvarchar,Error longvarchar,constraint pk_databaseupgradelog"
              + " primary key (ID))"; // NON-NLS
    };
  }

  private boolean databaseUpgradeLogTableExists(Connection connection) throws SQLException {
    if (migrationServices.tableExists(connection, "databaseupgradelog")) {
      if (!databaseUpgradeLogHasChangeLogName(connection)) {
        executeSQL(
            connection, "alter table databaseupgradelog add ChangeLogName varchar(200)"); // NON-NLS
        // Legacy tables created by older Liquibase installers may not have explicit primary key
        // constraints
        // Only add the constraint if it doesn't already exist
        try {
          executeSQL(
              connection,
              "alter table databaseupgradelog add constraint pk_databaseupgradelog"
                  + " primary key (ID)"); // NON-NLS
        } catch (SQLException e) {
          // Constraint already exists, silently ignore
          if (!e.getMessage().contains("already exists")) {
            throw e;
          }
        }
      }

      return true;
    }

    return false;
  }

  private boolean databaseUpgradeLogHasChangeLogName(Connection connection) throws SQLException {
    return migrationServices.columnExists(connection, "databaseupgradelog", "changelogname");
  }

  private void executeSQL(Connection connection, String sql) throws SQLException {
    try (Statement statement = connection.createStatement()) {
      statement.executeUpdate(sql);
    }
  }

  private static String quoteSql(String s) {
    return "'" + s.replace("'", "''") + "'";
  }
}
