package com.stano.schema.gensql.impl.h2;

import com.stano.schema.gensql.impl.common.ColumnTypeMapper;
import com.stano.schema.model.BooleanMode;
import com.stano.schema.model.Column;
import com.stano.schema.model.ColumnType;
import com.stano.schema.model.Schema;
import java.util.stream.Collectors;

public class H2ColumnTypeMapper extends ColumnTypeMapper {
  public H2ColumnTypeMapper(BooleanMode booleanMode, Schema schema) {
    super(booleanMode, schema);
  }

  @Override
  protected String getSequenceSql() {
    return "integer generated by default as identity (start with 1)";
  }

  @Override
  protected String getLongSequenceSql() {
    return "bigint generated by default as identity (start with 1)";
  }

  @Override
  protected String getTextSql(Column column) {
    return "character large object";
  }

  @Override
  protected String getCitextSql() {
    return "character large object";
  }

  @Override
  protected String getCstextSql() {
    return "character large object";
  }

  @Override
  protected String getBinarySql() {
    return "binary large object";
  }

  @Override
  protected String getUUIDSql(Column column) {
    return "uuid";
  }

  @Override
  protected String getTimestampTZSql() {
    return "timestamp with time zone";
  }

  @Override
  protected String getArraySql(Column column) {
    ColumnType elementType = column.getElementType();
    return switch (elementType) {
      case ColumnType.VARCHAR -> getVarcharSql(column) + " array";
      case ColumnType.CHAR -> getCharSql(column) + " array";
      case ColumnType.TEXT -> getTextSql(column) + " array";
      case ColumnType.DECIMAL -> getDecimalSql(column) + " array";
      default -> elementType.name() + " array";
    };
  }

  @Override
  protected String getEnumSql(Column column) {
    if (schema == null) {
      return "varchar(255)";
    }
    String values =
        schema.getEnumType(column.getEnumType()).getValues().stream()
            .map(v -> "'" + v.getCode() + "'")
            .collect(Collectors.joining(","));
    return "enum(" + values + ")";
  }
}
